# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Navigation_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navigation_2

pod 'SnapKit'

end

target 'Navigation_2_release' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navigation_2_release

pod 'SnapKit'

end

target 'StorageService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'

  # Pods for StorageService

end
